-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.16.0
    hooks:
    -   id: yapf
        args:
        - --in-place
        exclude: &EXCLUDE
          '(/dist/)|(egg-info/)|(/build/)|(/generated/)|(/.git/)|(/doc/)|(/\.idea/)|(/migrations/)'
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: trailing-whitespace
        exclude: *EXCLUDE
    -   id: flake8
        exclude: *EXCLUDE
