language:
  python
dist:
  trusty
sudo:
  required
python:
  - 2.7
before_install:
  - sudo apt-get -q update
  - sudo apt-get -q install -y build-essential python-dev libssl-dev libxml2-dev
    libxslt1-dev libffi-dev postgresql-server-dev-9.3 openssl libsmbclient-dev
    librsync-dev
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
script:
  # The bare Travis image comes with: Python 2.7.13, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
  - pip uninstall --yes pytest py
  # Travis clones the project to $TRAVIS_BUILD_DIR and cds there before running
  # the scripts.
  - ./dev_tools/src/d1_dev/setup-all.py --root $TRAVIS_BUILD_DIR develop
  - ./dev_tools/src/d1_dev/syspath.py
  - pip freeze
  - pip check || true
  - pytest --help
  - pytest --fixtures
  - pytest -n auto --cov=. --cov-report=term --cov-report=xml
after_success:
  # Submit results to Coveralls.io.
  # Coveralls has a requirement for requests >= 1.0.0, so we install it after
  # our packages to prevent it from pulling in the latest version, which is
  # likely to conflict with the fixed version our packages pull in.
  - coveralls
