language:
  python
dist:
  xenial
sudo:
  required
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - libffi-dev
      - librsync-dev
      - libsmbclient-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - openssl
      - postgresql-10
      - postgresql-client-10
      - python-dev
      - python-pip
      - python3-dev
env:
  global:
    - PGPORT=5433
before_install:
#  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
#  - sudo apt-get -q update
install:
  - pip install --upgrade pip setuptools
script:
  # Travis clones the project to $TRAVIS_BUILD_DIR and CDs there before running
  # the scripts.
  - ls -l
  - pip install -r ./requirements.txt
  - python --version
  - python ./dev_tools/src/d1_dev/setup-all.py --root $TRAVIS_BUILD_DIR develop
  - python ./dev_tools/src/d1_dev/syspath.py
  - pip freeze
  - pip check || true
  - pytest --version
  # Create GMN template database
  - python ./gmn/src/d1_gmn/tests/mk_db_template.py
  # Run tests in parallel, using as many threads as are supported by Travis
  - pytest -n auto --cov-config .coveragerc --cov-report=term --cov-report=xml
#  - pytest -n auto --cov-config .coveragerc --cov-report=term --cov-report=xml ./gmn/src/d1_gmn/tests/test_sysmeta_extract.py -k 1010
  # --cov=.
  # --cov-config=tox.ini
  # --cov-config=coverage.cfg --cov-report=term --cov-report=xml
after_success:
  # Submit results to Coveralls.io.
  - coveralls
