language:
  python
dist:
  trusty
sudo:
  required
python:
  - 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential python-dev libssl-dev libxml2-dev libxslt1-dev libffi-dev postgresql-server-dev-9.3 openssl
install:
#  - pip install -r requirements.txt
  - pip install --upgrade pip
  - pip install --upgrade responses==0.5.1 coveralls setuptools
script:
  - python ./d1_common_python/src/setup.py develop --multi-version
  - python ./d1_libclient_python/src/setup.py develop --multi-version
  - python ./d1_client_cli/src/setup.py develop --multi-version
  - python ./d1_mn_generic/src/setup.py develop --multi-version
  - python ./d1_test_utilities_python/src/setup.py develop --multi-version
  - python -c "import sys; print '\n'.join(sys.path)"
  - nosetests --with-coverage --cover-package d1_common --cover-package d1_client --cover-package d1_test
after_success:
  coveralls
