language:
  python
dist:
  trusty
sudo:
  required
python:
  - 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential python-dev libssl-dev libxml2-dev libxslt1-dev libffi-dev postgresql-server-dev-9.3 openssl
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install coverage pytest-cov pytest-django
script:
  - cd $TRAVIS_BUILD_DIR/lib_common/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR/lib_client/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR/client_cli/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR/client_onedrive/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR/gmn/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR/test_utilities/src && python setup.py develop
  - cd $TRAVIS_BUILD_DIR
  # Debug
  - pip freeze
  - pip check
  - python -c "import sys; print '\n'.join(sys.path)"
  #- ls -l /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages
  # Run the tests
  - cd $TRAVIS_BUILD_DIR && pytest
after_success:
  # coveralls has a requirement for requests >= 1.0.0, so we install it after
  # our packages to prevent it from pulling in the latest version, which is
  # likely to conflict with the fixed version our packages pull in.
  - pip install coveralls
  - coveralls
