language:
  python
dist:
  trusty
sudo:
  required
python:
  - 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential python-dev libssl-dev libxml2-dev
    libxslt1-dev libffi-dev postgresql-server-dev-9.3 openssl
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install coverage pytest-cov pytest-django
script:
  # Travis clones the project to $TRAVIS_BUILD_DIR and cds there before running
  # the scripts.
  - python ./dev_tools/src/d1_dev/setup-all.py develop
  # Debug
  - pip freeze
  - pip check
  - python ./dev_tools/syspath.py
  # Run the tests
  - pytest
after_success:
  # Submit results to Coveralls.io.
  # Coveralls has a requirement for requests >= 1.0.0, so we install it after
  # our packages to prevent it from pulling in the latest version, which is
  # likely to conflict with the fixed version our packages pull in.
  - pip install coveralls
  - coveralls
