# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceobject',
            name='filename',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
