# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170527_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainIdToPersistentId',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
