# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chainidtopersistentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChainIdToPersistentId',
        ),
    ]
