# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_resourcemap_resourcemapmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-timestamp', 'id']},
        ),
    ]
