# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 02:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171017_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemapmember',
            old_name='ResourceMap',
            new_name='resource_map',
        ),
        migrations.AlterField(
            model_name='resourcemapmember',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcemapmember_did', to='app.IdNamespace'),
        ),
    ]
