# Generated by Django 2.0.3 on 2018-05-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171029_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AlterModelOptions(
            name='scienceobject',
            options={'ordering': ['modified_timestamp', 'id']},
        ),
    ]
