# Generated by Django 2.0.6 on 2018-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180518_1540'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['timestamp', 'id'], name='app_eventlo_timesta_c97888_idx'),
        ),
        migrations.AddIndex(
            model_name='scienceobject',
            index=models.Index(fields=['modified_timestamp', 'id'], name='app_science_modifie_76ef91_idx'),
        ),
    ]
