# Generated by Django 2.2 on 2019-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180901_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scienceobject',
            options={},
        ),
    ]
