#! /bin/bash
SRCPATH=`dirname $PWD`/src
if [[ -z $PYTHONPATH ]]; then
  export PYTHONPATH=$SRCPATH
elif [[ ! $PYTHONPATH == "*$SRCPATH*" ]]; then
  export PYTHONPATH="$SRCPATH:$PYTHONPATH"
fi
echo "PYTHONPATH = $PYTHONPATH"
make $1 $2 $3 $4 $5

