#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This work was created by participants in the DataONE project, and is
# jointly copyrighted by participating institutions in DataONE. For
# more information on DataONE, see our web site at http://dataone.org.
#
#   Copyright ${year}
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
'''
Module d1_common.tests.test_mime_multipart
==========================================

Unit tests for XML document comparison utility.

:Created: 2011-03-17
:Author: DataONE (dahl)
:Dependencies:
  - python 2.6
'''

import logging
import sys
import unittest
import StringIO
import re

from d1_common import xmlrunner
import d1_common.mime_multipart

sysmeta_xml_correct = u"""<?xml version="1.0" encoding="UTF-8"?>
<d1:systemMetadata xmlns:d1="http://dataone.org/service/types/0.5.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dataone.org/service/types/0.5.1 https://repository.dataone.org/software/cicore/tags/D1_SCHEMA_0_5_1/dataoneTypes.xsd">
    <!-- This instance document was auto generated by oXygen XML for testing purposes.
         It contains no useful information.
    -->
    <identifier>Identifier0</identifier>
    <objectFormat>eml://ecoinformatics.org/eml-2.0.1</objectFormat>
    <size>0</size>
    <submitter>uid=jones,o=NCEAS,dc=ecoinformatics,dc=org</submitter>
    <rightsHolder>uid=jones,o=NCEAS,dc=ecoinformatics,dc=org</rightsHolder>
    <obsoletes>Obsoletes0</obsoletes>
    <obsoletes>Obsoletes1</obsoletes>
    <obsoletedBy>ObsoletedBy0</obsoletedBy>
    <obsoletedBy>ObsoletedBy1</obsoletedBy>
    <derivedFrom>DerivedFrom0</derivedFrom>
    <derivedFrom>DerivedFrom1</derivedFrom>
    <describes>Describes0</describes>
    <describes>Describes1</describes>
    <describedBy>DescribedBy0</describedBy>
    <describedBy>DescribedBy1</describedBy>
    <checksum algorithm="SHA-1">2e01e17467891f7c933dbaa00e1459d23db3fe4f</checksum>
    <embargoExpires>2006-05-04T18:13:51.0Z</embargoExpires>
    <accessRule rule="allow" service="read" principal="Principal0"/>
    <accessRule rule="allow" service="read" principal="Principal1"/>
    <replicationPolicy replicationAllowed="true" numberReplicas="2">
        <preferredMemberNode>MemberNode12</preferredMemberNode>
        <preferredMemberNode>MemberNode13</preferredMemberNode>
        <blockedMemberNode>MemberNode6</blockedMemberNode>
        <blockedMemberNode>MemberNode7</blockedMemberNode>
    </replicationPolicy>
    <dateUploaded>2006-05-04T18:13:51.0Z</dateUploaded>
    <dateSysMetadataModified>2006-05-04T18:13:51.0Z</dateSysMetadataModified>
    <originMemberNode>OriginMemberNode0</originMemberNode>
    <authoritativeMemberNode>AuthoritativeMemberNode0</authoritativeMemberNode>
    <replica>
        <replicaMemberNode>ReplicaMemberNode0</replicaMemberNode>
        <replicationStatus>queued</replicationStatus>
        <replicaVerified>2006-05-04T18:13:51.0Z</replicaVerified>
    </replica>
    <replica>
        <replicaMemberNode>ReplicaMemberNode1</replicaMemberNode>
        <replicationStatus>queued</replicationStatus>
        <replicaVerified>2006-05-04T18:13:51.0Z</replicaVerified>
    </replica>
</d1:systemMetadata>
"""

binary_data = "\
\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\
\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\
\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c\x2d\x2e\x2f\
\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3a\x3b\x3c\x3d\x3e\x3f\
\x40\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4a\x4b\x4c\x4d\x4e\x4f\
\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5a\x5b\x5c\x5d\x5e\x5f\
\x60\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a\x6b\x6c\x6d\x6e\x6f\
\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7a\x7b\x7c\x7d\x7e\x7f\
\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\
\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\
\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\
\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\
\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\
\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\
\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\
\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff\
"

mmp_doc = "------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22field_name_1\x22\x0d\n\
\x0d\n\
field_value_1\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22field_name_2\x22\x0d\n\
\x0d\n\
field_value_2\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22field_name_3\x22\x0d\n\
\x0d\n\
field_value_3------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22file_key_1\x22\x3b\x20filename\x3d\x22file_name_1\x22\x0d\n\
Content-Type\x3a\x20application\x2foctet-stream\x0d\n\
\x0d\n\
\x3c\x3fxml\x20version\x3d\x221\x2e0\x22\x20encoding\x3d\x22UTF-8\x22\x3f\x3e\n\
\x3cd1\x3asystemMetadata\x20xmlns\x3ad1\x3d\x22http\x3a\x2f\x2fdataone\x2eorg\x2fservice\x2ftypes\x2f0\x2e5\x2e1\x22\n\
\x20xmlns\x3axsi\x3d\x22http\x3a\x2f\x2fwww\x2ew3\x2eorg\x2f2001\x2fXMLSchema-instance\x22\n\
\x20xsi\x3aschemaLocation\x3d\x22http\x3a\x2f\x2fdataone\x2eorg\x2fservice\x2ftypes\x2f0\x2e5\x2e1\x20https\x3a\x2f\x2frepository\x2edataone\x2eorg\x2fsoftware\x2fcicore\x2ftags\x2fD1_SCHEMA_0_5_1\x2fdataoneTypes\x2exsd\x22\x3e\n\
\x20\x20\x20\x20\x3c\x21--\x20This\x20instance\x20document\x20was\x20auto\x20generated\x20by\x20oXygen\x20XML\x20for\x20testing\x20purposes\x2e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x20It\x20contains\x20no\x20useful\x20information\x2e\n\
\x20\x20\x20\x20--\x3e\n\
\x20\x20\x20\x20\x3cidentifier\x3eIdentifier0\x3c\x2fidentifier\x3e\n\
\x20\x20\x20\x20\x3cobjectFormat\x3eeml\x3a\x2f\x2fecoinformatics\x2eorg\x2feml-2\x2e0\x2e1\x3c\x2fobjectFormat\x3e\n\
\x20\x20\x20\x20\x3csize\x3e0\x3c\x2fsize\x3e\n\
\x20\x20\x20\x20\x3csubmitter\x3euid\x3djones\x2co\x3dNCEAS\x2cdc\x3decoinformatics\x2cdc\x3dorg\x3c\x2fsubmitter\x3e\n\
\x20\x20\x20\x20\x3crightsHolder\x3euid\x3djones\x2co\x3dNCEAS\x2cdc\x3decoinformatics\x2cdc\x3dorg\x3c\x2frightsHolder\x3e\n\
\x20\x20\x20\x20\x3cobsoletes\x3eObsoletes0\x3c\x2fobsoletes\x3e\n\
\x20\x20\x20\x20\x3cobsoletes\x3eObsoletes1\x3c\x2fobsoletes\x3e\n\
\x20\x20\x20\x20\x3cobsoletedBy\x3eObsoletedBy0\x3c\x2fobsoletedBy\x3e\n\
\x20\x20\x20\x20\x3cobsoletedBy\x3eObsoletedBy1\x3c\x2fobsoletedBy\x3e\n\
\x20\x20\x20\x20\x3cderivedFrom\x3eDerivedFrom0\x3c\x2fderivedFrom\x3e\n\
\x20\x20\x20\x20\x3cderivedFrom\x3eDerivedFrom1\x3c\x2fderivedFrom\x3e\n\
\x20\x20\x20\x20\x3cdescribes\x3eDescribes0\x3c\x2fdescribes\x3e\n\
\x20\x20\x20\x20\x3cdescribes\x3eDescribes1\x3c\x2fdescribes\x3e\n\
\x20\x20\x20\x20\x3cdescribedBy\x3eDescribedBy0\x3c\x2fdescribedBy\x3e\n\
\x20\x20\x20\x20\x3cdescribedBy\x3eDescribedBy1\x3c\x2fdescribedBy\x3e\n\
\x20\x20\x20\x20\x3cchecksum\x20algorithm\x3d\x22SHA-1\x22\x3e2e01e17467891f7c933dbaa00e1459d23db3fe4f\x3c\x2fchecksum\x3e\n\
\x20\x20\x20\x20\x3cembargoExpires\x3e2006-05-04T18\x3a13\x3a51\x2e0Z\x3c\x2fembargoExpires\x3e\n\
\x20\x20\x20\x20\x3caccessRule\x20rule\x3d\x22allow\x22\x20service\x3d\x22read\x22\x20principal\x3d\x22Principal0\x22\x2f\x3e\n\
\x20\x20\x20\x20\x3caccessRule\x20rule\x3d\x22allow\x22\x20service\x3d\x22read\x22\x20principal\x3d\x22Principal1\x22\x2f\x3e\n\
\x20\x20\x20\x20\x3creplicationPolicy\x20replicationAllowed\x3d\x22true\x22\x20numberReplicas\x3d\x222\x22\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3cpreferredMemberNode\x3eMemberNode12\x3c\x2fpreferredMemberNode\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3cpreferredMemberNode\x3eMemberNode13\x3c\x2fpreferredMemberNode\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3cblockedMemberNode\x3eMemberNode6\x3c\x2fblockedMemberNode\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3cblockedMemberNode\x3eMemberNode7\x3c\x2fblockedMemberNode\x3e\n\
\x20\x20\x20\x20\x3c\x2freplicationPolicy\x3e\n\
\x20\x20\x20\x20\x3cdateUploaded\x3e2006-05-04T18\x3a13\x3a51\x2e0Z\x3c\x2fdateUploaded\x3e\n\
\x20\x20\x20\x20\x3cdateSysMetadataModified\x3e2006-05-04T18\x3a13\x3a51\x2e0Z\x3c\x2fdateSysMetadataModified\x3e\n\
\x20\x20\x20\x20\x3coriginMemberNode\x3eOriginMemberNode0\x3c\x2foriginMemberNode\x3e\n\
\x20\x20\x20\x20\x3cauthoritativeMemberNode\x3eAuthoritativeMemberNode0\x3c\x2fauthoritativeMemberNode\x3e\n\
\x20\x20\x20\x20\x3creplica\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicaMemberNode\x3eReplicaMemberNode0\x3c\x2freplicaMemberNode\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicationStatus\x3equeued\x3c\x2freplicationStatus\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicaVerified\x3e2006-05-04T18\x3a13\x3a51\x2e0Z\x3c\x2freplicaVerified\x3e\n\
\x20\x20\x20\x20\x3c\x2freplica\x3e\n\
\x20\x20\x20\x20\x3creplica\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicaMemberNode\x3eReplicaMemberNode1\x3c\x2freplicaMemberNode\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicationStatus\x3equeued\x3c\x2freplicationStatus\x3e\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x3creplicaVerified\x3e2006-05-04T18\x3a13\x3a51\x2e0Z\x3c\x2freplicaVerified\x3e\n\
\x20\x20\x20\x20\x3c\x2freplica\x3e\n\
\x3c\x2fd1\x3asystemMetadata\x3e\n\
\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22file_key_2\x22\x3b\x20filename\x3d\x22file_name_2\x22\x0d\n\
Content-Type\x3a\x20application\x2foctet-stream\x0d\n\
\x0d\n\
\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\n\
\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c-\x2e\x2f0123456789\x3a\x3b\x3c\x3d\x3e\x3f\x40ABCDEFGHIJKLMNOPQRSTUVWXYZ\x5b\x5c\x5d\x5e_\x60abcdefghijklmnopqrstuvwxyz\x7b\x7c\x7d\x7e\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22file_key_3\x22\x3b\x20filename\x3d\x22file_name_3\x22\x0d\n\
Content-Type\x3a\x20application\x2foctet-stream\x0d\n\
\x0d\n\
\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\n\
\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c-\x2e\x2f0123456789\x3a\x3b\x3c\x3d\x3e\x3f\x40ABCDEFGHIJKLMNOPQRSTUVWXYZ\x5b\x5c\x5d\x5e_\x60abcdefghijklmnopqrstuvwxyz\x7b\x7c\x7d\x7e\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24\x0d\n\
Content-Disposition\x3a\x20form-data\x3b\x20name\x3d\x22file_key_4\x22\x3b\x20filename\x3d\x22file_name_4\x22\x0d\n\
Content-Type\x3a\x20application\x2foctet-stream\x0d\n\
\x0d\n\
short_data\x0d\n\
------------6B3C785C-6290-11DF-A355-A6ECDED72085_\x24--\x0d\n\
"


class TestMimeMultipart(unittest.TestCase):
  def _convert_bin_to_string_literal(in_path, out_path):
    '''Convert a binary file to a Python string literal.
    '''
    i = open(in_path, 'rb')
    o = open(out_path, 'wb')
    while True:
      q = i.read(1)
      if q == '':
        break
      if q == '\n':
        o.write('\\n\\\n')
      elif re.match(r'[\w\n-]', q):
        o.write(q),
      else:
        o.write('\\x%02x' % ord(q))

  def test_correct_mmp_generation(self):
    headers = {
      'header_name_1': 'header_value_1',
      'header_name_2': 'header_value_2',
      'header_name_3': 'header_value_3',
    }

    fields = [
      ('field_name_1', 'field_value_1'),
      ('field_name_2', 'field_value_2'),
      ('field_name_3', 'field_value_3'),
    ]

    files = [
      ('file_key_1', 'file_name_1', sysmeta_xml_correct),
      ('file_key_2', 'file_name_2', binary_data),
      ('file_key_3', 'file_name_3', StringIO.StringIO(binary_data)),
      ('file_key_4', 'file_name_4', 'short_data'),
    ]

    mmp = d1_common.mime_multipart.multipart(headers, fields, files)
    self.assertEquals(mmp.read(), mmp_doc)

#===============================================================================

if __name__ == "__main__":
  argv = sys.argv
  if "--debug" in argv:
    logging.basicConfig(level=logging.DEBUG)
    argv.remove("--debug")
  if "--with-xunit" in argv:
    argv.remove("--with-xunit")
    unittest.main(argv=argv, testRunner=xmlrunner.XmlTestRunner(sys.stdout))
  else:
    unittest.main(argv=argv)
